version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bankapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-application
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: "u2iD#K)39jf_8aj!Ds@#S8fa@S0fsad83asdkldljl34S"
      JWT_EXPIRATION: 3600000
    depends_on:
      - db

volumes:
  pgdata:
