server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankapp
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: "u2iD#K)39jf_8aj!Ds@#S8fa@S0fsad83asdkldljl34S"
  expiration: 3600000
